[build]
base = "apps/docs/"
publish = "build/client"
command = "pnpm build"
framework = "vite"

[functions]
directory = ".netlify/functions-internal"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/assets/*"
[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"
